//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSolutionLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartID { get; set; }
        public string Name { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> StandardID { get; set; }
        public byte[] LastUpdateDate { get; set; }
        public int UserID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Standard Standard { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
